#!/bin/bash

# TOOLS #################

function terminate() {
	echo "$1"
	exit 1
}

# SCRIPT DEPS ###########

if ! which lua
then
	terminate "Lua interpreter is not installed"
fi
if ! which gen-slack-desc
then
	terminate "gen-slack-desc is needed to generate \
		slack-desc for this package"
fi

# CONFIG ################

arch="$(uname -m)"
PKGNAME=winctl_scripts
DIRS=( \
	/usr/bin \
)

# FILL LOCAL DIR ########
mkdir -p iii/install || terminate
for i in ${DIRS[@]}
do
	mkdir -p iii${i}
done

# slack-desc
gen-slack-desc $PKGNAME DESCR > iii/install/slack-desc || terminate

# copy files
cp findwin iii/usr/bin/findwin || terminate
cp modwin iii/usr/bin/modwin || terminate

# set perms
chmod -R 755 iii || terminate
chmod 755 iii/usr/bin/findwin || terminate
chmod 755 iii/usr/bin/modwin || terminate

# make pkg
pushd iii
pkgname="${PKGNAME}-1.0-${arch}-1.tgz"
rm "../$pkgname"
makepkg -l y -c n "../$pkgname"
popd
rm -r iii

